import type { District, Intervention, RiskFactor } from "./types"

export const rwandaDistricts: District[] = [
  // Kigali City (3 districts)
  {
    id: "gasabo",
    name: "Gasabo",
    province: "Kigali City",
    coordinates: [-1.9403, 30.1256],
    population: 530907,
    malnutritionRate: 10.2,
    stuntingRate: 24.5,
    wastingRate: 1.8,
    anemia: 15.3,
    vitaminADeficiency: 12.8,
    zincDeficiency: 19.2,
    riskScore: 28,
    riskLevel: "low",
  },
  {
    id: "kicukiro",
    name: "Kicukiro",
    province: "Kigali City",
    coordinates: [-1.9897, 30.1028],
    population: 318065,
    malnutritionRate: 11.5,
    stuntingRate: 26.2,
    wastingRate: 2.0,
    anemia: 16.8,
    vitaminADeficiency: 14.1,
    zincDeficiency: 20.5,
    riskScore: 32,
    riskLevel: "medium",
  },
  {
    id: "nyarugenge",
    name: "Nyarugenge",
    province: "Kigali City",
    coordinates: [-1.9706, 30.0587],
    population: 283714,
    malnutritionRate: 13.8,
    stuntingRate: 28.9,
    wastingRate: 2.3,
    anemia: 19.2,
    vitaminADeficiency: 16.5,
    zincDeficiency: 23.4,
    riskScore: 38,
    riskLevel: "medium",
  },

  // Eastern Province (7 districts)
  {
    id: "bugesera",
    name: "Bugesera",
    province: "Eastern Province",
    coordinates: [-2.2167, 30.2167],
    population: 363313,
    malnutritionRate: 19.5,
    stuntingRate: 36.8,
    wastingRate: 4.1,
    anemia: 29.7,
    vitaminADeficiency: 25.8,
    zincDeficiency: 32.5,
    riskScore: 72,
    riskLevel: "critical",
  },
  {
    id: "gatsibo",
    name: "Gatsibo",
    province: "Eastern Province",
    coordinates: [-1.6167, 30.4167],
    population: 433020,
    malnutritionRate: 17.8,
    stuntingRate: 34.2,
    wastingRate: 3.6,
    anemia: 27.1,
    vitaminADeficiency: 23.4,
    zincDeficiency: 30.1,
    riskScore: 65,
    riskLevel: "high",
  },
  {
    id: "kayonza",
    name: "Kayonza",
    province: "Eastern Province",
    coordinates: [-1.8833, 30.5833],
    population: 344157,
    malnutritionRate: 18.2,
    stuntingRate: 35.1,
    wastingRate: 3.8,
    anemia: 28.3,
    vitaminADeficiency: 24.6,
    zincDeficiency: 31.2,
    riskScore: 68,
    riskLevel: "high",
  },
  {
    id: "kirehe",
    name: "Kirehe",
    province: "Eastern Province",
    coordinates: [-2.2167, 30.7167],
    population: 339467,
    malnutritionRate: 20.1,
    stuntingRate: 37.5,
    wastingRate: 4.3,
    anemia: 30.8,
    vitaminADeficiency: 26.9,
    zincDeficiency: 33.7,
    riskScore: 75,
    riskLevel: "critical",
  },
  {
    id: "ngoma",
    name: "Ngoma",
    province: "Eastern Province",
    coordinates: [-2.1667, 30.5333],
    population: 338586,
    malnutritionRate: 18.9,
    stuntingRate: 35.8,
    wastingRate: 3.9,
    anemia: 29.1,
    vitaminADeficiency: 25.3,
    zincDeficiency: 31.8,
    riskScore: 70,
    riskLevel: "critical",
  },
  {
    id: "nyagatare",
    name: "Nyagatare",
    province: "Eastern Province",
    coordinates: [-1.3, 30.3333],
    population: 466944,
    malnutritionRate: 16.5,
    stuntingRate: 32.9,
    wastingRate: 3.4,
    anemia: 25.8,
    vitaminADeficiency: 22.1,
    zincDeficiency: 28.9,
    riskScore: 61,
    riskLevel: "high",
  },
  {
    id: "rwamagana",
    name: "Rwamagana",
    province: "Eastern Province",
    coordinates: [-1.9486, 30.4347],
    population: 310216,
    malnutritionRate: 17.2,
    stuntingRate: 33.6,
    wastingRate: 3.5,
    anemia: 26.4,
    vitaminADeficiency: 22.8,
    zincDeficiency: 29.5,
    riskScore: 63,
    riskLevel: "high",
  },

  // Northern Province (5 districts)
  {
    id: "burera",
    name: "Burera",
    province: "Northern Province",
    coordinates: [-1.4833, 29.8833],
    population: 338886,
    malnutritionRate: 17.5,
    stuntingRate: 34.1,
    wastingRate: 3.2,
    anemia: 26.8,
    vitaminADeficiency: 23.2,
    zincDeficiency: 29.8,
    riskScore: 64,
    riskLevel: "high",
  },
  {
    id: "gakenke",
    name: "Gakenke",
    province: "Northern Province",
    coordinates: [-1.6833, 29.8],
    population: 338586,
    malnutritionRate: 16.8,
    stuntingRate: 33.2,
    wastingRate: 3.0,
    anemia: 25.5,
    vitaminADeficiency: 22.1,
    zincDeficiency: 28.7,
    riskScore: 60,
    riskLevel: "high",
  },
  {
    id: "gicumbi",
    name: "Gicumbi",
    province: "Northern Province",
    coordinates: [-1.5833, 30.0667],
    population: 430903,
    malnutritionRate: 15.9,
    stuntingRate: 31.8,
    wastingRate: 2.8,
    anemia: 24.2,
    vitaminADeficiency: 20.9,
    zincDeficiency: 27.5,
    riskScore: 57,
    riskLevel: "high",
  },
  {
    id: "musanze",
    name: "Musanze",
    province: "Northern Province",
    coordinates: [-1.5, 29.6333],
    population: 368267,
    malnutritionRate: 14.8,
    stuntingRate: 30.5,
    wastingRate: 2.6,
    anemia: 22.8,
    vitaminADeficiency: 19.6,
    zincDeficiency: 26.2,
    riskScore: 52,
    riskLevel: "medium",
  },
  {
    id: "rulindo",
    name: "Rulindo",
    province: "Northern Province",
    coordinates: [-1.7833, 30.0667],
    population: 287681,
    malnutritionRate: 15.2,
    stuntingRate: 31.1,
    wastingRate: 2.7,
    anemia: 23.5,
    vitaminADeficiency: 20.3,
    zincDeficiency: 26.9,
    riskScore: 54,
    riskLevel: "medium",
  },

  // Southern Province (8 districts)
  {
    id: "gisagara",
    name: "Gisagara",
    province: "Southern Province",
    coordinates: [-2.5833, 29.8333],
    population: 307765,
    malnutritionRate: 21.8,
    stuntingRate: 39.2,
    wastingRate: 4.5,
    anemia: 33.5,
    vitaminADeficiency: 29.3,
    zincDeficiency: 36.1,
    riskScore: 80,
    riskLevel: "critical",
  },
  {
    id: "huye",
    name: "Huye",
    province: "Southern Province",
    coordinates: [-2.5972, 29.7389],
    population: 381900,
    malnutritionRate: 20.5,
    stuntingRate: 37.8,
    wastingRate: 4.2,
    anemia: 31.8,
    vitaminADeficiency: 27.8,
    zincDeficiency: 34.5,
    riskScore: 76,
    riskLevel: "critical",
  },
  {
    id: "kamonyi",
    name: "Kamonyi",
    province: "Southern Province",
    coordinates: [-2.0167, 29.9833],
    population: 340501,
    malnutritionRate: 19.8,
    stuntingRate: 36.9,
    wastingRate: 4.0,
    anemia: 30.5,
    vitaminADeficiency: 26.7,
    zincDeficiency: 33.3,
    riskScore: 73,
    riskLevel: "critical",
  },
  {
    id: "muhanga",
    name: "Muhanga",
    province: "Southern Province",
    coordinates: [-2.0833, 29.75],
    population: 323642,
    malnutritionRate: 20.2,
    stuntingRate: 37.5,
    wastingRate: 4.1,
    anemia: 31.2,
    vitaminADeficiency: 27.3,
    zincDeficiency: 34.0,
    riskScore: 75,
    riskLevel: "critical",
  },
  {
    id: "nyamagabe",
    name: "Nyamagabe",
    province: "Southern Province",
    coordinates: [-2.5, 29.5],
    population: 355451,
    malnutritionRate: 22.5,
    stuntingRate: 40.1,
    wastingRate: 4.7,
    anemia: 34.8,
    vitaminADeficiency: 30.5,
    zincDeficiency: 37.2,
    riskScore: 83,
    riskLevel: "critical",
  },
  {
    id: "nyanza",
    name: "Nyanza",
    province: "Southern Province",
    coordinates: [-2.35, 29.75],
    population: 323719,
    malnutritionRate: 21.1,
    stuntingRate: 38.5,
    wastingRate: 4.3,
    anemia: 32.5,
    vitaminADeficiency: 28.5,
    zincDeficiency: 35.3,
    riskScore: 78,
    riskLevel: "critical",
  },
  {
    id: "nyaruguru",
    name: "Nyaruguru",
    province: "Southern Province",
    coordinates: [-2.6167, 29.4167],
    population: 317117,
    malnutritionRate: 23.1,
    stuntingRate: 41.2,
    wastingRate: 4.9,
    anemia: 35.9,
    vitaminADeficiency: 31.8,
    zincDeficiency: 38.5,
    riskScore: 86,
    riskLevel: "critical",
  },
  {
    id: "ruhango",
    name: "Ruhango",
    province: "Southern Province",
    coordinates: [-2.2333, 29.7833],
    population: 315930,
    malnutritionRate: 20.8,
    stuntingRate: 38.2,
    wastingRate: 4.2,
    anemia: 32.1,
    vitaminADeficiency: 28.1,
    zincDeficiency: 34.8,
    riskScore: 77,
    riskLevel: "critical",
  },

  // Western Province (7 districts)
  {
    id: "karongi",
    name: "Karongi",
    province: "Western Province",
    coordinates: [-2.0, 29.3833],
    population: 333715,
    malnutritionRate: 19.2,
    stuntingRate: 36.1,
    wastingRate: 3.7,
    anemia: 29.8,
    vitaminADeficiency: 26.0,
    zincDeficiency: 32.6,
    riskScore: 71,
    riskLevel: "critical",
  },
  {
    id: "ngororero",
    name: "Ngororero",
    province: "Western Province",
    coordinates: [-1.8833, 29.5333],
    population: 317074,
    malnutritionRate: 20.5,
    stuntingRate: 37.8,
    wastingRate: 4.0,
    anemia: 31.5,
    vitaminADeficiency: 27.6,
    zincDeficiency: 34.3,
    riskScore: 76,
    riskLevel: "critical",
  },
  {
    id: "nyabihu",
    name: "Nyabihu",
    province: "Western Province",
    coordinates: [-1.6667, 29.5],
    population: 288618,
    malnutritionRate: 18.5,
    stuntingRate: 35.3,
    wastingRate: 3.6,
    anemia: 28.7,
    vitaminADeficiency: 25.1,
    zincDeficiency: 31.5,
    riskScore: 68,
    riskLevel: "high",
  },
  {
    id: "nyamasheke",
    name: "Nyamasheke",
    province: "Western Province",
    coordinates: [-2.3333, 29.0833],
    population: 310943,
    malnutritionRate: 21.5,
    stuntingRate: 39.0,
    wastingRate: 4.4,
    anemia: 33.2,
    vitaminADeficiency: 29.1,
    zincDeficiency: 36.0,
    riskScore: 79,
    riskLevel: "critical",
  },
  {
    id: "rubavu",
    name: "Rubavu",
    province: "Western Province",
    coordinates: [-1.6833, 29.2667],
    population: 388586,
    malnutritionRate: 17.8,
    stuntingRate: 34.5,
    wastingRate: 3.4,
    anemia: 27.5,
    vitaminADeficiency: 24.0,
    zincDeficiency: 30.3,
    riskScore: 65,
    riskLevel: "high",
  },
  {
    id: "rusizi",
    name: "Rusizi",
    province: "Western Province",
    coordinates: [-2.4833, 28.9167],
    population: 348586,
    malnutritionRate: 20.8,
    stuntingRate: 38.5,
    wastingRate: 4.2,
    anemia: 32.3,
    vitaminADeficiency: 28.3,
    zincDeficiency: 35.1,
    riskScore: 78,
    riskLevel: "critical",
  },
  {
    id: "rutsiro",
    name: "Rutsiro",
    province: "Western Province",
    coordinates: [-1.9833, 29.3333],
    population: 293717,
    malnutritionRate: 19.5,
    stuntingRate: 36.8,
    wastingRate: 3.8,
    anemia: 30.2,
    vitaminADeficiency: 26.4,
    zincDeficiency: 33.0,
    riskScore: 72,
    riskLevel: "critical",
  },
]

export const riskFactors: RiskFactor[] = [
  {
    name: "Rainfall Deficit",
    impact: 0.85,
    category: "environmental",
    description: "Below-average rainfall affecting crop yields",
  },
  {
    name: "Market Access",
    impact: 0.72,
    category: "infrastructure",
    description: "Limited access to food markets in rural areas",
  },
  {
    name: "Household Income",
    impact: 0.68,
    category: "economic",
    description: "Low household income limiting food diversity",
  },
  {
    name: "Health Facility Coverage",
    impact: 0.61,
    category: "health",
    description: "Inadequate health facility coverage for nutrition services",
  },
  {
    name: "Soil Quality",
    impact: 0.58,
    category: "environmental",
    description: "Degraded soil affecting nutrient content in crops",
  },
  {
    name: "Education Level",
    impact: 0.54,
    category: "economic",
    description: "Low maternal education affecting nutrition practices",
  },
]

export const interventions: Intervention[] = [
  {
    id: "int-1",
    title: "Biofortified Crop Distribution",
    description: "Distribute vitamin A-enriched orange sweet potato and iron-rich beans to high-risk districts",
    targetDistricts: [
      "gisagara",
      "huye",
      "kamonyi",
      "muhanga",
      "nyamagabe",
      "nyanza",
      "nyaruguru",
      "ruhango",
      "bugesera",
      "gatsibo",
      "kayonza",
      "kirehe",
      "ngoma",
      "nyagatare",
      "rwamagana",
    ],
    estimatedImpact: 0.82,
    feasibility: 0.78,
    cost: "$2.5M - $3.2M",
    timeframe: "12-18 months",
    priority: "high",
    category: "agriculture",
  },
  {
    id: "int-2",
    title: "Community Health Worker Training",
    description: "Train CHWs on nutrition counseling and micronutrient supplementation",
    targetDistricts: [
      "gisagara",
      "huye",
      "kamonyi",
      "muhanga",
      "nyamagabe",
      "nyanza",
      "nyaruguru",
      "ruhango",
      "burera",
      "gakenke",
      "gicumbi",
      "musanze",
      "rulindo",
    ],
    estimatedImpact: 0.75,
    feasibility: 0.85,
    cost: "$800K - $1.2M",
    timeframe: "6-9 months",
    priority: "high",
    category: "health",
  },
  {
    id: "int-3",
    title: "School Feeding Program Expansion",
    description: "Expand fortified school meals to cover all primary schools in high-risk areas",
    targetDistricts: [
      "bugesera",
      "gatsibo",
      "kayonza",
      "kirehe",
      "ngoma",
      "nyagatare",
      "rwamagana",
      "burera",
      "gakenke",
      "gicumbi",
      "musanze",
      "rulindo",
      "gisagara",
      "huye",
      "kamonyi",
      "muhanga",
      "nyamagabe",
      "nyanza",
      "nyaruguru",
      "ruhango",
    ],
    estimatedImpact: 0.71,
    feasibility: 0.72,
    cost: "$4.5M - $5.8M",
    timeframe: "18-24 months",
    priority: "high",
    category: "nutrition",
  },
  {
    id: "int-4",
    title: "Market Infrastructure Development",
    description: "Build rural market centers to improve food access and diversity",
    targetDistricts: [
      "ngororero",
      "nyabihu",
      "nyamasheke",
      "rusizi",
      "rutsiro",
      "bugesera",
      "gatsibo",
      "kayonza",
      "kirehe",
      "ngoma",
      "nyagatare",
      "rwamagana",
    ],
    estimatedImpact: 0.68,
    feasibility: 0.65,
    cost: "$6.2M - $8.5M",
    timeframe: "24-36 months",
    priority: "medium",
    category: "infrastructure",
  },
  {
    id: "int-5",
    title: "Maternal Nutrition Education",
    description: "Community-based nutrition education for pregnant and lactating mothers",
    targetDistricts: [
      "gasabo",
      "kicukiro",
      "nyarugenge",
      "bugesera",
      "gatsibo",
      "kayonza",
      "kirehe",
      "ngoma",
      "nyagatare",
      "rwamagana",
      "burera",
      "gakenke",
      "gicumbi",
      "musanze",
      "rulindo",
      "gisagara",
      "huye",
      "kamonyi",
      "muhanga",
      "nyamagabe",
      "nyanza",
      "nyaruguru",
      "ruhango",
      "karongi",
      "ngororero",
      "nyabihu",
      "nyamasheke",
      "rusizi",
      "rutsiro",
    ],
    estimatedImpact: 0.64,
    feasibility: 0.88,
    cost: "$500K - $750K",
    timeframe: "6-12 months",
    priority: "medium",
    category: "education",
  },
]
