"use client"

import { useState } from "react"
import { Card } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { Checkbox } from "@/components/ui/checkbox"
import { ArrowLeft, FileText, Download, Loader2, CheckCircle2, AlertCircle } from "lucide-react"
import Link from "next/link"
import type { PolicyBrief } from "@/lib/types"
import { rwandaDistricts } from "@/lib/mock-data"

export default function PolicyBriefsPage() {
  const [sector, setSector] = useState<string>("health")
  const [selectedDistricts, setSelectedDistricts] = useState<string[]>([])
  const [generatedBrief, setGeneratedBrief] = useState<PolicyBrief | null>(null)
  const [loading, setLoading] = useState(false)

  const handleDistrictToggle = (districtId: string) => {
    setSelectedDistricts((prev) =>
      prev.includes(districtId) ? prev.filter((id) => id !== districtId) : [...prev, districtId],
    )
  }

  const generateBrief = async () => {
    setLoading(true)
    try {
      const response = await fetch("/api/policy-briefs", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          sector,
          targetDistricts: selectedDistricts.length > 0 ? selectedDistricts : undefined,
        }),
      })
      const data = await response.json()
      setGeneratedBrief(data)
    } catch (error) {
      console.error("Failed to generate brief:", error)
    } finally {
      setLoading(false)
    }
  }

  const downloadBrief = () => {
    if (!generatedBrief) return

    const content = `
POLICY BRIEF: ${generatedBrief.title}
Sector: ${generatedBrief.sector.toUpperCase()}
Generated: ${new Date(generatedBrief.generatedAt).toLocaleDateString()}

EXECUTIVE SUMMARY
${generatedBrief.summary}

KEY FINDINGS
${generatedBrief.keyFindings.map((f, i) => `${i + 1}. ${f}`).join("\n")}

RECOMMENDATIONS
${generatedBrief.recommendations.map((r, i) => `${i + 1}. ${r}`).join("\n")}

TARGET DISTRICTS
${generatedBrief.targetDistricts
  .map((id) => {
    const district = rwandaDistricts.find((d) => d.id === id)
    return district?.name || id
  })
  .join(", ")}

---
Generated by NutriVision Rwanda - Geospatial Early Warning System
    `.trim()

    const blob = new Blob([content], { type: "text/plain" })
    const url = URL.createObjectURL(blob)
    const a = document.createElement("a")
    a.href = url
    a.download = `policy-brief-${generatedBrief.sector}-${Date.now()}.txt`
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
  }

  return (
    <div className="min-h-screen bg-background">
      {/* Header */}
      <header className="border-b bg-card">
        <div className="container mx-auto px-4 py-4">
          <div className="flex items-center gap-4">
            <Button variant="ghost" size="sm" asChild>
              <Link href="/">
                <ArrowLeft className="w-4 h-4 mr-2" />
                Back
              </Link>
            </Button>
            <div>
              <h1 className="text-2xl font-bold">Policy Brief Generator</h1>
              <p className="text-sm text-muted-foreground">
                Generate sector-specific policy recommendations based on data analysis
              </p>
            </div>
          </div>
        </div>
      </header>

      {/* Main Content */}
      <main className="container mx-auto px-4 py-6">
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
          {/* Configuration Panel */}
          <div className="lg:col-span-1 space-y-4">
            <Card className="p-6">
              <h2 className="text-lg font-semibold mb-4">Brief Configuration</h2>

              <div className="space-y-4">
                <div className="space-y-2">
                  <label className="text-sm font-medium">Sector</label>
                  <Select value={sector} onValueChange={setSector}>
                    <SelectTrigger>
                      <SelectValue />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="health">Health</SelectItem>
                      <SelectItem value="agriculture">Agriculture</SelectItem>
                      <SelectItem value="education">Education</SelectItem>
                    </SelectContent>
                  </Select>
                </div>

                <div className="space-y-2">
                  <label className="text-sm font-medium">Target Districts</label>
                  <p className="text-xs text-muted-foreground mb-2">Leave empty to auto-select high-risk districts</p>
                  <div className="space-y-2">
                    {rwandaDistricts.map((district) => (
                      <div key={district.id} className="flex items-center space-x-2">
                        <Checkbox
                          id={district.id}
                          checked={selectedDistricts.includes(district.id)}
                          onCheckedChange={() => handleDistrictToggle(district.id)}
                        />
                        <label
                          htmlFor={district.id}
                          className="text-sm font-medium leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70 cursor-pointer"
                        >
                          {district.name}
                          <Badge
                            variant={district.riskLevel === "critical" ? "destructive" : "secondary"}
                            className="ml-2 text-xs"
                          >
                            {district.riskLevel}
                          </Badge>
                        </label>
                      </div>
                    ))}
                  </div>
                </div>

                <Button onClick={generateBrief} disabled={loading} className="w-full">
                  {loading ? (
                    <>
                      <Loader2 className="w-4 h-4 mr-2 animate-spin" />
                      Generating...
                    </>
                  ) : (
                    <>
                      <FileText className="w-4 h-4 mr-2" />
                      Generate Brief
                    </>
                  )}
                </Button>
              </div>
            </Card>

            {/* Info Card */}
            <Card className="p-4 bg-muted/50">
              <div className="flex items-start gap-2">
                <AlertCircle className="w-5 h-5 text-primary mt-0.5" />
                <div className="space-y-1">
                  <p className="text-sm font-medium">About Policy Briefs</p>
                  <p className="text-xs text-muted-foreground leading-relaxed">
                    Policy briefs synthesize data from NISR surveys, predictive models, and root cause analysis to
                    provide actionable recommendations for stakeholders.
                  </p>
                </div>
              </div>
            </Card>
          </div>

          {/* Generated Brief Display */}
          <div className="lg:col-span-2">
            {!generatedBrief ? (
              <Card className="p-12 text-center">
                <FileText className="w-16 h-16 mx-auto text-muted-foreground mb-4" />
                <h3 className="text-lg font-semibold mb-2">No Brief Generated</h3>
                <p className="text-sm text-muted-foreground">
                  Select a sector and target districts, then click Generate Brief to create a policy recommendation
                  document.
                </p>
              </Card>
            ) : (
              <Card className="p-8">
                <div className="space-y-6">
                  {/* Header */}
                  <div className="flex items-start justify-between pb-4 border-b">
                    <div className="flex-1">
                      <Badge variant="outline" className="mb-2 capitalize">
                        {generatedBrief.sector} Sector
                      </Badge>
                      <h2 className="text-2xl font-bold text-balance mb-2">{generatedBrief.title}</h2>
                      <p className="text-sm text-muted-foreground">
                        Generated on{" "}
                        {new Date(generatedBrief.generatedAt).toLocaleDateString("en-US", {
                          year: "numeric",
                          month: "long",
                          day: "numeric",
                        })}
                      </p>
                    </div>
                    <Button onClick={downloadBrief} variant="outline" size="sm">
                      <Download className="w-4 h-4 mr-2" />
                      Download
                    </Button>
                  </div>

                  {/* Executive Summary */}
                  <div className="space-y-2">
                    <h3 className="text-lg font-semibold">Executive Summary</h3>
                    <p className="text-sm text-muted-foreground leading-relaxed">{generatedBrief.summary}</p>
                  </div>

                  {/* Key Findings */}
                  <div className="space-y-3">
                    <h3 className="text-lg font-semibold">Key Findings</h3>
                    <div className="space-y-2">
                      {generatedBrief.keyFindings.map((finding, index) => (
                        <div key={index} className="flex items-start gap-3 p-3 bg-muted/50 rounded-lg">
                          <div className="flex items-center justify-center w-6 h-6 rounded-full bg-primary/10 text-primary text-xs font-semibold flex-shrink-0 mt-0.5">
                            {index + 1}
                          </div>
                          <p className="text-sm leading-relaxed">{finding}</p>
                        </div>
                      ))}
                    </div>
                  </div>

                  {/* Recommendations */}
                  <div className="space-y-3">
                    <h3 className="text-lg font-semibold">Recommendations</h3>
                    <div className="space-y-2">
                      {generatedBrief.recommendations.map((rec, index) => (
                        <div
                          key={index}
                          className="flex items-start gap-3 p-3 border-l-4 border-primary bg-card rounded-r-lg"
                        >
                          <CheckCircle2 className="w-5 h-5 text-primary flex-shrink-0 mt-0.5" />
                          <p className="text-sm leading-relaxed">{rec}</p>
                        </div>
                      ))}
                    </div>
                  </div>

                  {/* Target Districts */}
                  <div className="space-y-2 pt-4 border-t">
                    <h3 className="text-sm font-semibold">Target Districts</h3>
                    <div className="flex flex-wrap gap-2">
                      {generatedBrief.targetDistricts.map((districtId) => {
                        const district = rwandaDistricts.find((d) => d.id === districtId)
                        return (
                          <Badge key={districtId} variant="secondary">
                            {district?.name || districtId}
                          </Badge>
                        )
                      })}
                    </div>
                  </div>
                </div>
              </Card>
            )}
          </div>
        </div>
      </main>
    </div>
  )
}
